version: "3.8"
services:
  web:

    container_name: "aspnetcoreapp_container"
    image: "aspnetcoreapp_image"
    build:
      context: .
      dockerfile: aspnetcore.dockerfile
    ports:
      - "8080:5000"
    networks:
      - aspnetcoreapp-network

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password # Change this on production
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge